from typing import List

from incendium.helper.types import String

def send_high_priority_email(
    subject: String, body: String, to: List[String]
) -> None: ...
def send_html_email(
    subject: String, body: String, to: List[String], priority: String = ...
) -> None: ...
def send_plain_text_email(
    subject: String, body: String, to: List[String], priority: String = ...
) -> None: ...
