from typing import Dict, Optional, Tuple, Union

from incendium.helper.types import Number, String
from incendium.user import IncendiumUser
from java.util import Date

def get_function_name() -> String: ...
def get_timer(date: Union[Date, long]) -> String: ...
def get_timestamp(value: int) -> String: ...
def set_locale(user: IncendiumUser) -> None: ...
def validate_form(
    strings: Optional[Dict[String, String]] = ...,
    numbers: Optional[Dict[String, Number]] = ...,
    collections: Optional[Dict[String, Number]] = ...,
) -> Tuple[bool, String]: ...
