from typing import Optional

from incendium.helper.types import DictStringAny, String

def swap_to(path: String, params: Optional[DictStringAny] = ...) -> None: ...
def swap_windows(
    from_path: String, to_path: String, params: Optional[DictStringAny] = ...
) -> None: ...
