name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: test ${{ matrix.python-version }}

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Python
        id: cache-python
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: py${{ matrix.python-version }}-${{ hashFiles('tox.ini', 'requirements/ci.txt')  }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --requirement requirements/ci.txt

      - name: Pick environment to run
        run: |
          import codecs; import os; import sys
          env = "TOXENV=py{}{}\n".format(*sys.version_info[:2])
          print(f"Picked:\n{env}for {sys.version}")
          with codecs.open(os.environ["GITHUB_ENV"], "a", "utf-8") as file_handler:
              file_handler.write(env)
        shell: python

      - name: Cache tox
        id: cache-tox
        uses: actions/cache@v3
        with:
          path: .tox
          key: ${{ runner.os }}-tox-${{ hashFiles('tox.ini', 'requirements.txt') }}

      - name: Run tests
        run: |
          tox
