name: pr-build

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/pr-build.yml
      - .github/workflows/tox-uv.yml
      - stubs/**
      - pyproject.toml
      - requirements.txt
      - tox.ini

jobs:
  test:
    uses: ./.github/workflows/tox-uv.yml
    with:
      uv-version: 'latest'
      python-versions: '3.9 3.10 3.11 3.12'
