name: pr-build

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/pr-build.yml
      - stubs/**
      - pyproject.toml
      - requirements.txt
      - tox.ini

jobs:
  test:
    uses: ./.github/workflows/tox-uv.yml
