name: publish

on:
  release:
    types:
      - published

jobs:
  publish:
    uses: coatl-dev/workflows/.github/workflows/pypi-upload.yml@v2.1.0
    with:
      python-version: "3.10"
    secrets:
      pypi-token: ${{ secrets.PYPI_API_TOKEN }}
