name: publish

on:
  release:
    types:
      - published

jobs:
  tox:
    uses: coatl-dev/workflows/.github/workflows/tox-gh.yml@v4
    with:
      python-versions: '["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]'

  pypi-publish:
    needs:
      - tox
    uses: coatl-dev/workflows/.github/workflows/pypi-upload.yml@v4
    secrets:
      password: ${{ secrets.PYPI_API_TOKEN_INCENDIUM_STUBS }}
