name: publish

on:
  release:
    types:
      - published

jobs:
  tox:
    uses: coatl-dev/workflows/.github/workflows/tox.yml@coatl

  pypi-publish:
    needs:
      - tox
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: coatl-dev/actions/pypi-upload@coatl
        with:
          python-version: '3.11'
          password: ${{ secrets.PYPI_API_TOKEN }}
