on:
  workflow_call:
    inputs:
      uv-version:
        description: >-
          The version of uv to install.
        required: false
        type: string
        default: 'latest'
      python-versions:
        description: A list of Python versions.
        required: true
        type: string

jobs:
  tox:
    name: tox-uv
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJSON(inputs.python-versions) }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
        with:
          version: ${{ inputs.uv-version }}
          cache-dependency-glob: |
            tox.ini

      - name: Install dependencies
        run: |
          uv tool install tox --with tox-uv
        env:
          UV_PYTHON: ${{ matrix.python-version }}

      - name: Run tox
        run: |
          tox
